production: &production
  adapter: postgresql
  host: postgres
  database: canvas
  username: postgres
  open: true
  password: <%= ENV["DB_PASSWORD"] %>
  encoding: utf8
  timeout: 5000
  prepared_statements: false
  use_qualified_names: true
  shard_name: public
  schema_search_path: "''"

