# See doc/docker/README.md or https://github.com/instructure/canvas-lms/tree/master/doc/docker
version: '2.3'
services:
  web:
    image: ${WEB_IMAGE}

  jobs:
    image: ${WEB_IMAGE}

  postgres:
    image: ${POSTGRES_IMAGE}
