version: '3.7'
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - ./pgadmin/conf/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_LOGIN_BANNER: "'PGAdmin for \"${COMPOSE_PROJECT_NAME}\" project.'"
    ports:
      - "${PGADMIN_PORT}:80"
